In [17]:
import pandas as pd

In [22]:
df = pd.read_csv("/Users/aasnayemgazzalichowdhury/Desktop/SuperStoreOrders.csv")
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/11,6/1/11,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/11,8/1/11,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/11,5/1/11,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/11,5/1/11,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/11,8/1/11,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [23]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [24]:
# Convert date
df['order_date'] = pd.to_datetime(df['order_date'])
df['order_date']

df['ship_date'] = pd.to_datetime(df['ship_date'])
df['ship_date']

0       2011-06-01
1       2011-08-01
2       2011-05-01
3       2011-05-01
4       2011-08-01
           ...
51285   2015-04-01
51286   2015-05-01
51287   2015-02-01
51288   2015-06-01
51289   2015-04-01
Name: ship_date, Length: 51290, dtype: datetime64[ns]

In [25]:
# Create time feautures
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()
df['day_name'] = df['order_date'].dt.day_name()

In [26]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sales,quantity,discount,profit,shipping_cost,order_priority,year,month,month_name,day_name
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,408,2,0.0,106.1400,35.46,Medium,2011,1,January,Saturday
1,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,120,3,0.1,36.0360,9.72,Medium,2011,1,January,Saturday
2,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,66,4,0.0,29.6400,8.17,High,2011,1,January,Saturday
3,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,45,3,0.5,-26.0550,4.82,High,2011,1,January,Saturday
4,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,114,5,0.1,37.7700,4.70,Medium,2011,1,January,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,2014-12-31,2015-04-01,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,14,2,0.2,4.5188,0.89,Medium,2014,12,December,Wednesday
51286,MO-2014-2560,2014-12-31,2015-05-01,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,4,1,0.0,0.4200,0.49,Medium,2014,12,December,Wednesday
51287,MX-2014-110527,2014-12-31,2015-02-01,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,26,3,0.0,12.3600,0.35,Medium,2014,12,December,Wednesday
51288,MX-2014-114783,2014-12-31,2015-06-01,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,7,1,0.0,0.5600,0.20,Medium,2014,12,December,Wednesday
51289,CA-2014-156720,2014-12-31,2015-04-01,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,3,3,0.2,-0.6048,0.17,Medium,2014,12,December,Wednesday

In [34]:
# Convert sales column to numeric
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')

# Check if any bad values became null
print(df['sales'].isnull().sum())

# Create customer spend
customer_spend = df.groupby('customer_name')['sales'].sum().reset_index()

customer_spend.rename(
    columns={'sales':'customer_total_sales'},
    inplace=True
)

df = df.merge(customer_spend,on='customer_name')

2630

In [35]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,order_priority,year,month,month_name,day_name,customer_total_sales_x,customer_total_sales_y,customer_total_sales_x,customer_total_sales_y,customer_total_sales
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Medium,2011,1,January,Saturday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0
1,RS-2011-4710,2011-02-14,2011-02-20,Standard Class,Toby Braunhardt,Consumer,Kaluga,Russia,EMEA,EMEA,...,Low,2011,2,February,Monday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0
2,CA-2011-8490,2011-02-24,2011-03-03,Standard Class,Toby Braunhardt,Consumer,Ontario,Canada,Canada,Canada,...,Low,2011,2,February,Thursday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0
3,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,High,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0
4,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,High,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,Medium,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0
51286,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,Medium,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0
51287,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,Medium,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0
51288,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,Medium,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0
51289,CA-2014-130309,2014-12-18,2014-12-22,Standard Class,Giulietta Baptist,Consumer,Virginia,United States,US,South,...,High,2014,12,December,Thursday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0

In [36]:
# Create customer segmentation

def segment_customer(x):
    if x > 5000:
        return 'High Value'
    elif x > 1000:
        return 'Medium Value'
    else:
        return 'Low Value'

df['customer_segment'] = df['customer_total_sales'].apply(segment_customer)

In [37]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,year,month,month_name,day_name,customer_total_sales_x,customer_total_sales_y,customer_total_sales_x,customer_total_sales_y,customer_total_sales,customer_segment
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,2011,1,January,Saturday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
1,RS-2011-4710,2011-02-14,2011-02-20,Standard Class,Toby Braunhardt,Consumer,Kaluga,Russia,EMEA,EMEA,...,2011,2,February,Monday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
2,CA-2011-8490,2011-02-24,2011-03-03,Standard Class,Toby Braunhardt,Consumer,Ontario,Canada,Canada,Canada,...,2011,2,February,Thursday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
3,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
4,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51286,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51287,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51288,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51289,CA-2014-130309,2014-12-18,2014-12-22,Standard Class,Giulietta Baptist,Consumer,Virginia,United States,US,South,...,2014,12,December,Thursday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value

In [38]:
# Top products
print(
    df.groupby('product_name')['sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

# Sales by category
print(
    df.groupby('category')['sales']
    .sum()
)

# Sales by month
print(
    df.groupby('month_name')['sales']
    .sum()
)

# Customer segments count
print(
    df['customer_segment'].value_counts()
)

# Preview final dataset
print(df.head())

product_name
Eldon File Cart, Single Width                         31319.0
Rogers File Cart, Single Width                        22645.0
Tenex File Cart, Single Width                         20778.0
Smead File Cart, Single Width                         20775.0
Office Star Executive Leather Armchair, Adjustable    19355.0
Fellowes Lockers, Industrial                          19172.0
Smead Lockers, Industrial                             18648.0
Hewlett Copy Machine, Color                           16849.0
Rogers Lockers, Blue                                  16494.0
Fellowes Lockers, Wire Frame                          16470.0
Name: sales, dtype: float64
category
Furniture          2406605.0
Office Supplies    2790258.0
Technology         2638265.0
Name: sales, dtype: float64
month_name
April        531722.0
August       736964.0
December     826735.0
February     455796.0
January      475695.0
July         554111.0
June         745063.0
March        557679.0
May          592614.0
November     877597.0
October      697796.0
September    783356.0
Name: sales, dtype: float64
High Value      50321
Medium Value      969
Name: customer_segment, dtype: int64
         order_id order_date  ship_date       ship_mode    customer_name  \
0    AG-2011-2040 2011-01-01 2011-06-01  Standard Class  Toby Braunhardt
1    RS-2011-4710 2011-02-14 2011-02-20  Standard Class  Toby Braunhardt
2    CA-2011-8490 2011-02-24 2011-03-03  Standard Class  Toby Braunhardt
3  MX-2011-169201 2011-03-06 2011-07-06  Standard Class  Toby Braunhardt
4  MX-2011-169201 2011-03-06 2011-07-06  Standard Class  Toby Braunhardt

    segment        state   country  market  region  ...  year month  \
0  Consumer  Constantine   Algeria  Africa  Africa  ...  2011     1
1  Consumer       Kaluga    Russia    EMEA    EMEA  ...  2011     2
2  Consumer      Ontario    Canada  Canada  Canada  ...  2011     2
3  Consumer       Bogota  Colombia   LATAM   South  ...  2011     3
4  Consumer       Bogota  Colombia   LATAM   South  ...  2011     3

  month_name  day_name                             customer_total_sales_x  \
0    January  Saturday  4082757125861820608962823160152330238215656235...
1   February    Monday  4082757125861820608962823160152330238215656235...
2   February  Thursday  4082757125861820608962823160152330238215656235...
3      March    Sunday  4082757125861820608962823160152330238215656235...
4      March    Sunday  4082757125861820608962823160152330238215656235...

                              customer_total_sales_y  \
0  4082757125861820608962823160152330238215656235...
1  4082757125861820608962823160152330238215656235...
2  4082757125861820608962823160152330238215656235...
3  4082757125861820608962823160152330238215656235...
4  4082757125861820608962823160152330238215656235...

                              customer_total_sales_x  customer_total_sales_y  \
0  4082757125861820608962823160152330238215656235...                 10412.0
1  4082757125861820608962823160152330238215656235...                 10412.0
2  4082757125861820608962823160152330238215656235...                 10412.0
3  4082757125861820608962823160152330238215656235...                 10412.0
4  4082757125861820608962823160152330238215656235...                 10412.0

   customer_total_sales customer_segment
0               10412.0       High Value
1               10412.0       High Value
2               10412.0       High Value
3               10412.0       High Value
4               10412.0       High Value

[5 rows x 30 columns]

In [39]:
df.groupby('category')['profit'].sum().sort_values(ascending=False)
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,year,month,month_name,day_name,customer_total_sales_x,customer_total_sales_y,customer_total_sales_x,customer_total_sales_y,customer_total_sales,customer_segment
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,2011,1,January,Saturday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
1,RS-2011-4710,2011-02-14,2011-02-20,Standard Class,Toby Braunhardt,Consumer,Kaluga,Russia,EMEA,EMEA,...,2011,2,February,Monday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
2,CA-2011-8490,2011-02-24,2011-03-03,Standard Class,Toby Braunhardt,Consumer,Ontario,Canada,Canada,Canada,...,2011,2,February,Thursday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
3,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
4,MX-2011-169201,2011-03-06,2011-07-06,Standard Class,Toby Braunhardt,Consumer,Bogota,Colombia,LATAM,South,...,2011,3,March,Sunday,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,4082757125861820608962823160152330238215656235...,10412.0,10412.0,High Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51286,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51287,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51288,US-2014-111906,2014-10-22,2014-10-27,Standard Class,Giulietta Baptist,Consumer,Santo Domingo,Dominican Republic,LATAM,Caribbean,...,2014,10,October,Wednesday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value
51289,CA-2014-130309,2014-12-18,2014-12-22,Standard Class,Giulietta Baptist,Consumer,Virginia,United States,US,South,...,2014,12,December,Thursday,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,1241149888872150397152718559432120525516887831...,10880.0,10880.0,High Value

In [41]:
# Drop duplicate/corrupted columns
df = df.drop(
    columns=[
        'customer_total_sales_x',
        'customer_total_sales_y'
    ],
    errors='ignore'
)

# Check remaining columns
print(df.columns)

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year',
       'month', 'month_name', 'day_name', 'customer_total_sales',
       'customer_segment'],
      dtype='object')

In [44]:
# Export final cleaned dataset to Excel
df.to_csv("/Users/aasnayemgazzalichowdhury/Desktop/final_sales_dataset.csv", index=False)